export const PRICING = {
  EXTRA_PRICE: 1.0,
  RIPPCHEN_SPECIAL_OLD_PRICE: 14.9,
  RIPPCHEN_SPECIAL_NEW_PRICE: 10.9,
  SCHNITZEL_SPECIAL_OLD_PRICE: 12.9,
  SCHNITZEL_SPECIAL_NEW_PRICE: 9.9
} as const;
