export const TIME_CONFIG = {
  MIN_ADVANCE_MINUTES: 20,
  OPENING_HOUR_MONDAY: 16,
  OPENING_HOUR_OTHER_DAYS: 12,
  CLOSING_HOUR: 22,
  CLOSING_MINUTE: 30,
  TIME_INTERVAL_MINUTES: 5,
  WEEKDAY_MONDAY: 1
} as const;

export const DAYS_OF_WEEK = {
  MONDAY: 1,
  TUESDAY: 2,
  WEDNESDAY: 3,
  THURSDAY: 4,
  FRIDAY: 5,
  SATURDAY: 6,
  SUNDAY: 0
} as const;
